
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hp
 */

import javax.swing.*;
                                                                                                                         
public class Configuration extends javax.swing.JFrame {                                                                                                                 

    public static boolean TutorialMode = true; //Para indicar si el modo de tutorial esta activado
    
    /**
     * Creates new form Configuration
     */
    public Configuration() {
        initComponents();
        
        if (TutorialMode) {
            BtnTutorial.setSelected(true);
        } else {
            BtnClasico.setSelected(true);
        }
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgModes = new javax.swing.ButtonGroup();
        Titulo = new javax.swing.JLabel();
        BtnTutorial = new javax.swing.JRadioButton();
        BtnClasico = new javax.swing.JRadioButton();
        GuardarConfig = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        Titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Titulo.setText("CONFIGURACION");

        BgModes.add(BtnTutorial);
        BtnTutorial.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        BtnTutorial.setText("Modo Tutorial");

        BgModes.add(BtnClasico);
        BtnClasico.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        BtnClasico.setText("Modo Clasico");

        GuardarConfig.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        GuardarConfig.setText("GUARDAR");
        GuardarConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarConfigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnClasico)
                    .addComponent(BtnTutorial)
                    .addComponent(Titulo))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GuardarConfig)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Titulo)
                .addGap(37, 37, 37)
                .addComponent(BtnTutorial)
                .addGap(28, 28, 28)
                .addComponent(BtnClasico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(GuardarConfig)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarConfigActionPerformed
        // TODO add your handling code here:
        if (BtnTutorial.isSelected()) {
            TutorialMode = true;
        } else if (BtnClasico.isSelected()) {
            TutorialMode = false;
        } else {
            JOptionPane.showMessageDialog(this, "Porfavor selecciona un modo antes de guardar.", "Configuracion", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        JOptionPane.showMessageDialog(this, "Configuracion gaurdada.", "Guardado", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_GuardarConfigActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BgModes;
    private javax.swing.JRadioButton BtnClasico;
    private javax.swing.JRadioButton BtnTutorial;
    private javax.swing.JButton GuardarConfig;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
