package MarvelStratego;


import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hp
 */

import javax.swing.*;
                                                                                                                         
public class Configuration extends javax.swing.JFrame {                                                                                                                 

    public static boolean TutorialMode = false; //Siempre falso
    
    /**
     * Creates new form Configuration
     */
    public Configuration() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Configuracion Marvel Stratego");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgModes = new javax.swing.ButtonGroup();
        Titulo = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();
        ModoInfo = new javax.swing.JLabel();
        DescripcionClasico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        Titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(204, 0, 0));
        Titulo.setText("CONFIGURACION");

        BtnAceptar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnAceptar.setText("ACEPTAR");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        ModoInfo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ModoInfo.setForeground(java.awt.Color.green);
        ModoInfo.setText("MODO CLASICO ACTIVADO");

        DescripcionClasico.setForeground(new java.awt.Color(102, 102, 102));
        DescripcionClasico.setText("Fichas ocultas para maxima estrategia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ModoInfo)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnAceptar)
                        .addGap(149, 149, 149))))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(Titulo)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DescripcionClasico, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ModoInfo)
                .addGap(18, 18, 18)
                .addComponent(DescripcionClasico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(BtnAceptar)
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        // TODO add your handling code here:
        TutorialMode = false;
        
        JOptionPane.showMessageDialog(this, """
                                            Configuracion confirmada!
                                            
                                             MODO CLASICO:
                                                • Fichas ocultas activadas
                                                • Click en tus fichas para revelar identidad
                                                • Estrategia maxima habilitada
                                            
                                            Listo para la batalla Marvel!""", 
                                            "Configuracion Lista", 
                                            JOptionPane.INFORMATION_MESSAGE);
        //Cerrar la ventana
        this.dispose();
    }//GEN-LAST:event_BtnAceptarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BgModes;
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JLabel DescripcionClasico;
    private javax.swing.JLabel ModoInfo;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
